### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by ed-sparkes** [dd4t/DD4T.Caching.ApacheMQ#1]
Hi, 

Not finding much help online of how to actually use this, any scope for a little more documentation in the readme. I have added the package to my project and added the bits to my web.config. Is there anything to add to my code to actually use these web config entries. I am using the autofac DD4t library to load DD4T 

i.e. 

```
builder.UseDD4T();
builder.Build();
```

would i do something like this ...

```
 builder.RegisterType<JMSMessageProvider>().As<IMessageProvider>().SingleInstance();
 builder.UseDD4T();
```

Thanks, Ed

**Comment by quirijnslings** [comment]
It took us a while but we finally got around to this. Our apologies for the delay, hope it is still helpful to someone. See https://github.com/dd4t/DD4T.Caching.ApacheMQ for installation notes.
